[package]
name = "order-service"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
common = { workspace = true }
salvo = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }

log = { workspace = true }

lazy_static = { workspace = true }


chrono = { workspace = true }

uuid = { workspace = true }
toml = { workspace = true }

anyhow = { workspace = true }